### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CleverSource** [FuginCZ/Lightwork#1]
If you plan to make this a full on engine, maybe something kind of like AeroGameFramework documentation is key. I haven't spent my time looking at the code and obviously something is wrong if I have to look at the code to understand how to use the framework. 😛 

You probably plan to have documentation but I just wanted to recommend it.

**Comment by FuginCZ** [comment]
Yeah, I can make the documentation.
Thank you for warning me about it.
